# Generated by Django 4.1.3 on 2023-01-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_reviews_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='status',
        ),
        migrations.AddField(
            model_name='destinations',
            name='cover',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='destinations',
            name='type',
            field=models.CharField(choices=[('open', 'OPEN'), ('close', 'CLOSE')], default='Open', max_length=10),
        ),
    ]
