# Generated by Django 4.1.3 on 2023-01-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_destinations_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='category',
            field=models.CharField(choices=[('CAFERESTO', 'Cafe-Resto'), ('GYM', 'Gym'), ('PARK', 'Park'), ('SITEHISTORIQUE', 'Site historique'), ('HOTEL', 'Hotel'), ('BAR', 'Bar')], max_length=20),
        ),
    ]
