# Generated by Django 4.1.3 on 2023-01-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_destinations_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_taxi', models.TextField()),
                ('num_taxi', models.IntegerField()),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
