# Generated by Django 4.1.3 on 2023-01-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_taxi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='cover',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
