# Generated by Django 4.1.3 on 2023-01-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_destinations_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='restaurent',
            new_name='restaurant',
        ),
    ]
