# Generated by Django 4.1.3 on 2023-01-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_restaurent_package_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='type',
            field=models.CharField(choices=[('Open', 'OPEN'), ('Close', 'CLOSE')], default='Open', max_length=10),
        ),
    ]
